version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
    cap_add:
      - SYS_NICE
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
    environment:
      - EDITOR=vim