version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/rails-docker-usa/src #github repository
    steps:
      - checkout:
          path: ~/rails-docker-usa
      - ruby/install:
          version: '2.7' #Using bundle command

  test:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.5 #circleci mysql version
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1" # my PC IP ADRESS
      RAILS_ENV: test
    working_directory: ~/rails-docker-usa/src
    steps:
      - checkout:
          path: ~/rails-docker-usa
      - ruby/install:
          version: '2.7'
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test

  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test:
            requires:
            - build